name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Only trigger on version tags

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        run: |
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
          CIBW_SKIP: pp*  # Skip PyPy if not needed
          CIBW_TEST_REQUIRES: pytest  # Optional: install pytest for testing
          CIBW_TEST_COMMAND: "pytest tests"  # Optional: run tests in the 'tests' directory

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.8.4
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
