name: Publish Python Package

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when pushing a tag that starts with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel twine cibuildwheel

      - name: Build the package
        env:
          CIBW_PLATFORM: "linux"  # Can specify different platforms if needed
        run: |
          cibuildwheel --output-dir dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
